// File: lib/firebase_options.dart
// Generated by Antigravity - placeholder configurations for AgriGroww Firebase initialization.
// Replace these parameters with your real credentials from the Firebase Console or by running `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkRC4Q_Q7Vxv0e-mtImzN7JM0Ucn3P0Y',
    appId: '1:701827917765:android:9732b70e87510e6ce10dac', // Replace with web App ID if you add web
    messagingSenderId: '701827917765',
    projectId: 'agrigroww-2005',
    authDomain: 'agrigroww-2005.firebaseapp.com',
    storageBucket: 'agrigroww-2005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdkRC4Q_Q7Vxv0e-mtImzN7JM0Ucn3P0Y',
    appId: '1:701827917765:android:9732b70e87510e6ce10dac',
    messagingSenderId: '701827917765',
    projectId: 'agrigroww-2005',
    storageBucket: 'agrigroww-2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdkRC4Q_Q7Vxv0e-mtImzN7JM0Ucn3P0Y',
    appId: '1:701827917765:android:9732b70e87510e6ce10dac', // Replace with iOS App ID if you add iOS
    messagingSenderId: '701827917765',
    projectId: 'agrigroww-2005',
    storageBucket: 'agrigroww-2005.firebasestorage.app',
    iosBundleId: 'com.example.agrigroww',
  );
}
